name: Lint

on:
  pull_request:
    branches: [main, changeset-release/**]
  push:
    branches: [main, changeset-release/**]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint:ci
