name: Test

on:
  pull_request:
    branches: [main, changeset-release/**]
  push:
    branches: [main, changeset-release/**]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test
